### ISSUE TITLE
su -c 的執行

### ISSUE THREAD

**Issue by webeasyplay** [VeiZhang/AndroidExec#1]
请问如何执行root 提权操作
我使用kotlin
val command = "am force-stop packag"
时，log印出onProgress: Unknown id: am

`          
val mTask  = CommandTask.Builder().commands("su").commands( command).build()

    mTask.deploy(Shell())`

Thx

**Comment by VeiZhang** [comment]
@webeasyplay 杀死应用这种需要root权限，或者`su`命令，这种首先的条件是你的应用得有root权限，在应用中执行命令跟在adb命令行执行，权限不一样。

**Comment by webeasyplay** [comment]
我用模拟器肯定有root权限

**Comment by VeiZhang** [comment]
@webeasyplay 目前遇到`权限拒绝`，`命令没有识别`的情况。
我用你的命令执行是`权限拒绝`。
你试试用demo测试命令，看看是什么结果。
